### ISSUE TITLE
is it possible to have always the same file name each time you run the Action ?

### ISSUE THREAD

**Issue by amcaw** [flameddd/screenshots-ci-action#14]
Every time the script run, a file with a new name is created. What if you want to have always the same name and overwrite the file in your repo when commiting ?

**Comment by flameddd** [comment]
need to add this feature. sorry I toooo busy recently, although this is a small feature.  
I will take a look if I have time in the weekend

**Comment by amcaw** [comment]
Thanks !

**Comment by flameddd** [comment]
@amcaw , sorry for late, `v2.0.0` released.

Check `noCommitHashFileName` option from document
- https://github.com/flameddd/screenshots-ci-action

thanks
