### ISSUE TITLE
Is it possible to post screenshots on pull request's comment ?

### ISSUE THREAD

**Issue by flameddd** [flameddd/screenshots-ci-action#6]
as title
- need some time to do some test

**Comment by flameddd** [comment]
# `v1.1.1`: add Telegram
- https://github.com/flameddd/screenshots-ci-action/blob/master/README.Telegram.md

Now, `screenshots-ci-action` are able to send screenshots to **Telegram**  
![img4](https://github.com/flameddd/screenshots-ci-action/raw/master/asset/telegram4.jpg)  
![img2](https://github.com/flameddd/screenshots-ci-action/raw/master/asset/telegram2.jpg)

**Comment by flameddd** [comment]
# Maybe, Maybe, Maybe there are some trick way could be possible

- https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c

![image](https://user-images.githubusercontent.com/22259196/97712800-ea005000-1af9-11eb-9a13-97f294c4a5ca.png)

flow
1. load all image
2. turn to base64
3. write clipboard
4. simulate ctrl + V to trigger upload
5. scan Text 
6. loop

**Comment by LukaHarambasic** [comment]
I would appreciate screenshots in the comments a lot.

Currently I have the following workflow: go to Actions > Screenshot Action > (scroll down) > Download Artifcats

It would be really nice if a direct download link to the artifact could be posted in the comments. 

Thanks a lot!!

**Comment by flameddd** [comment]
Hi @LukaHarambasic 
thank you let me know there is someone need this feature.
 
 I will try in next few weeks. And let you know if I have any progress.

**Comment by artyrcheek** [comment]
I agree that would be great!

**Comment by N-Shar-ma** [comment]
I created this [workflow](https://github.com/N-Shar-ma/testing-stuff/blob/master/.github/workflows/main.yml) which uploads the screenshots to imgur and then posts them in a comment to the PR. It works well when the index.html is just a few characters, but always times out when it's anything more complex. I can't figure out why

Someone might want to take a look! Both the passed and failed (timed out) runs are in the Actions tab of the same repository

**Comment by flameddd** [comment]
`v1.2.0` released, see [README.PR](https://github.com/flameddd/screenshots-ci-action/blob/master/README.PR.md) document for more detail.  

cc @LukaHarambasic @artyrcheek @N-Shar-ma  and @mattvb91 , thanks

**Comment by flameddd** [comment]
>... It works well when the index.html is just a few characters, but always times out when it's anything more complex. I can't figure out why

I would consider update puppeteer's `waitUntil`, from `networkidle0` to `networkidle2`

**Comment by flameddd** [comment]
@N-Shar-ma `v2.0.0` released, `waitUntil` option been added, thanks
- https://github.com/flameddd/screenshots-ci-action
